### ISSUE TITLE
Handle App Links

### ISSUE THREAD

**Issue by pinyaoting** [doublesp/Coherence#32]
User should be able to share an [app link](https://developer.android.com/training/app-links/index.html) from our app, tapping on the link would direct them back to our app.

Task Breakdown:
1. modify our current [Implicit Intent](https://github.com/doublesp/Coherence/blob/master/app/src/main/java/com/doublesp/coherence/actions/IdeaPreviewActionHandler.java#L23-L30) to share a link instead, the link should contains a uuid of the list. (You can use hard-coded value for now, e.g. uuid=1234)
2. create a separate activity to handle the link. (You don't need to implement the actual UI for the activity, just extract the uuid from the link, and show it in a TextView.)

**Comment by ShawnDuan** [comment]
👌
