### ISSUE TITLE
Recipe page needs to be scrollable

### ISSUE THREAD

**Issue by santhoshsachindran** [doublesp/Coherence#97]
Currently if recipe is too big, the page does not scroll, so complete recipe not visible to user. We need to make that text scrollable - Issue seen with recipe "Bourbon Layer Cake with Bourbon Ganache and Milk Chocolate Buttercream"

Also i am thinking we should have the image visible at the top and as we come down it should probably become a dark background to read the instructions clearly.

**Comment by pinyaoting** [comment]
Already fixed.
